name: Pull Request check

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
    paths:
      - src/**/*.*
jobs:
  test:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Clone the main repo
        run: cd .. && sudo /usr/bin/git clone https://github.com/${{ github.repository }} main && cd -
      - name: Check if the PR is acceptable
        run: |
          diff -q ./.github/ ../main/.github
      - name: Copy test suites from main repo to PR
        run: cp ../main/tests/*.* tests/
      - name: Get rid of the main repo's clone
        run: sudo rm -rf ../main
      - name: Validate package.json
        run: yarn validate-package-json
      - name: Install dependencies
        run: yarn
      - name: Run ESLint
        run: yarn lint
      - name: Build code
        run: yarn build
      - name: Run main test suites
        run: yarn test
      - name: Report the build failed (if it did)
        if: failure()
        uses: jungwinter/comment@v1
        with:
          type: create
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.pull_request.number }}
          body: |
            Hi, @${{ github.event.pull_request.user.login }}! I'm afraid the CI check for PR #${{ github.event.pull_request.number }} has failed!  
            Don't worry, it'll run again if you commit any changes to this PR.
      - name: Label PR as "CI failed" (if it did)
        if: failure()
        uses: actions/labeler@v4
        with:
          sync-labels: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}

